In [2]:
from github import Github
import datetime
import pandas as pd
import numpy as np
import os

In [3]:
g = Github('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')
repo = g.get_repo('immich-app/immich')

In [4]:
pulls = repo.get_pulls(state='all')
pull_data =[]
for pr in pulls:
    pull_info= {
        'Pr_state': pr.state,
        'Created_at': pr.created_at,
        'Updated_at': pr.updated_at,
        'Additions': pr.additions,
        'Commits': pr.commits,
        'Merged_at': pr.merged_at 
    }
    pull_data.append(pull_info)

In [ ]:
pr_df =pd.DataFrame(pull_data)
pr_df.to_csv('pr.csv', index=False)

In [ ]:
pr_df

,Pr_state,Created_at,Updated_at,Additions,Commits,Merged_at
0,open,2024-06-08 22:16:00+00:00,2024-06-08 22:16:01+00:00,8,1,NaT
1,closed,2024-06-08 19:45:48+00:00,2024-06-08 19:51:37+00:00,854,1,2024-06-08 19:51:36+00:00
2,open,2024-06-08 18:23:28+00:00,2024-06-08 21:41:06+00:00,133,4,NaT
3,closed,2024-06-08 17:01:24+00:00,2024-06-08 17:55:20+00:00,2,1,2024-06-08 17:55:19+00:00
4,closed,2024-06-08 10:44:16+00:00,2024-06-08 10:50:15+00:00,1,1,2024-06-08 10:50:14+00:00
...,...,...,...,...,...,...
4318,closed,2022-02-08 17:24:07+00:00,2024-03-12 15:28:50+00:00,343,2,2022-02-08 17:24:49+00:00
4319,closed,2022-02-08 05:42:11+00:00,2024-02-13 22:15:20+00:00,10715,2,2022-02-08 05:42:35+00:00
4320,closed,2022-02-07 02:28:28+00:00,2024-03-09 23:22:33+00:00,133,3,2022-02-07 02:31:32+00:00
4321,closed,2022-02-06 18:08:06+00:00,2024-03-09 04:16:39+00:00,53,2,2022-02-06 19:06:01+00:00
4322,closed,2022-02-06 06:07:43+00:00,2024-05-29 17:11:53+00:00,581,14,2022-02-06 06:07:56+00:00

In [4]:
issues = repo.get_issues(state='all')
issue_data=[]
for issue in issues:
    issue_info = {
        'Created_at': issue.created_at,
        'Closed_at': issue.closed_at,
        'State': issue.state,
        'Labels': [label.name for label in issue.labels],
        'Assignees': [assignee.login for assignee in issue.assignees]
    }
    issue_data.append(issue_info)

In [6]:
issue_df = pd.DataFrame(issue_data)
issue_df.to_csv('issue.csv',index=False)

In [7]:
issue_df

,Created_at,Closed_at,State,Labels,Assignees
0,2024-06-09 21:48:28+00:00,NaT,open,[📱mobile],[]
1,2024-06-09 19:07:24+00:00,2024-06-09 19:18:02+00:00,closed,[github_actions],[]
2,2024-06-09 17:43:42+00:00,2024-06-09 19:48:47+00:00,closed,[],[]
3,2024-06-09 16:30:27+00:00,2024-06-09 19:18:41+00:00,closed,[maintenance],[]
4,2024-06-09 13:29:28+00:00,NaT,open,[],[]
...,...,...,...,...,...
7261,2022-02-06 06:37:29+00:00,2022-02-08 06:27:24+00:00,closed,[enhancement],[]
7262,2022-02-06 06:37:24+00:00,2022-02-08 03:44:44+00:00,closed,[enhancement],[]
7263,2022-02-06 06:37:08+00:00,2022-02-06 06:50:47+00:00,closed,[],[]
7264,2022-02-06 06:07:43+00:00,2022-02-06 06:07:56+00:00,closed,[],[]
7265,2022-02-05 07:04:44+00:00,2022-02-06 06:26:15+00:00,closed,[feature],[alextran1502]

In [6]:
start_date = datetime.datetime(2022, 1,1)
end_date = datetime.datetime(2023,1,1)
commit_data = []
def get_commits():
    commits = repo.get_commits(since=start_date, until=end_date)
    for commit in commits:
        files_changed = [file.filename for file in commit.files]
        files_changed_count = len(files_changed)
        all_checks_passed = all(status == "success" for status in commit.get_combined_status().statuses)
        additions = commit.stats.additions,
        contributor = commit.author
        commit_info= {
            'Commit_message': commit.commit.message,
            'Author_email': commit.commit.author.email,
            'Author_name': commit.commit.author.name,
            'Updated at': commit.commit.author.date,
            'Files_changed': files_changed,
            'Files_changed_count': files_changed_count,
            'Contributor': contributor,
            'All_checks_passed': all_checks_passed,
            'Additions': additions 
        }
        commit_data.append(commit_info)

In [ ]:
get_commits()

In [7]:
start_date = datetime.datetime(2023, 2,1)
end_date = datetime.datetime(2024, 1, 1)
get_commits()

In [23]:
commit_df_tmp = pd.DataFrame(commit_data)
commit_df_tmp.to_csv('commit_data_tmp.csv', index=False)

In [ ]:
start_date = datetime.datetime(2024, 2,1)
end_date = datetime.datetime(2024, 7, 6)
get_commits()

In [ ]:
df = pd.DataFrame(commit_data)
df.to_csv('commit_data.csv', index=False)

In [ ]:
df

,Commit_message,Author_email,Author_name,Updated at,Files_changed,Files_changed_count,Contributor,All_checks_passed,Additions
0,fix(web): pick deleted user (#1237),jrasm91@gmail.com,Jason Rasmussen,2022-12-31 03:30:48+00:00,[web/src/lib/components/album-page/user-select...,1,"NamedUser(login=""jrasm91"")",True,"(2,)"
1,feat(deployment): Consistent container names (...,btom1990@googlemail.com,bt90,2022-12-30 16:30:28+00:00,"[docker/docker-compose.dev.yml, docker/docker-...",3,"NamedUser(login=""bt90"")",True,"(12,)"
2,refactor(server): imports and repository token...,jrasm91@gmail.com,Jason Rasmussen,2022-12-30 13:22:06+00:00,"[server/apps/cli/src/app.module.ts, server/app...",81,"NamedUser(login=""jrasm91"")",True,"(130,)"
3,fix nginx conf file (#1229),vedhavyas.singareddi@gmail.com,Vedhavyas Singareddi,2022-12-30 11:12:24+00:00,[nginx/nginx.conf],1,"NamedUser(login=""vedhavyas"")",True,"(4,)"
4,Docs: Github -> GitHub (#1221),emaltonator@gmail.com,John P,2022-12-30 04:45:25+00:00,"[docs/docs/overview/help.md, docs/docs/overvie...",3,"NamedUser(login=""Emalton"")",True,"(4,)"
...,...,...,...,...,...,...,...,...,...
4006,feat(web): improved album view UI & album card...,66187991+azroberts8@users.noreply.github.com,Andrew Roberts,2024-02-02 02:50:14+00:00,[web/src/lib/components/album-page/album-card....,3,"NamedUser(login=""azroberts8"")",True,"(6,)"
4007,chore: simplify API build (#6841),322311+benmccann@users.noreply.github.com,Ben McCann,2024-02-01 22:55:21+00:00,"[open-api/typescript-sdk/package.json, open-ap...",4,"NamedUser(login=""benmccann"")",True,"(11,)"
4008,fix(web): Admin Settings banner/scrolling issu...,66187991+azroberts8@users.noreply.github.com,Andrew Roberts,2024-02-01 21:05:30+00:00,[web/src/routes/admin/system-settings/+page.sv...,1,"NamedUser(login=""azroberts8"")",True,"(44,)"
4009,docs: provide details on storage engine album ...,50788000+mmomjian@users.noreply.github.com,mmomjian,2024-02-01 03:28:30+00:00,[docs/docs/partials/_storage-template.md],1,"NamedUser(login=""mmomjian"")",True,"(1,)"
4010,docs(ml): hardware acceleration (#6821),101130780+mertalev@users.noreply.github.com,Mert,2024-02-01 01:12:57+00:00,"[docker/hwaccel.ml.yml, docker/hwaccel.transco...",5,"NamedUser(login=""mertalev"")",True,"(91,)"

In [19]:
import os
import pandas as pd
df = pd.read_csv(os.path.join('commit_data.csv'))
pr_df = pd.read_csv(os.path.join('pr.csv'))
issue_df = pd.read_csv(os.path.join('issue.csv'))

In [20]:
df

,Unnamed: 0,Commit_message,Author_email,Author_name,Updated at,Files_changed,Files_changed_count,Contributor,All_checks_passed,Additions
0,0,fix(web): pick deleted user (#1237),jrasm91@gmail.com,Jason Rasmussen,2022-12-31 03:30:48,['web/src/lib/components/album-page/user-selec...,1,NaN,True,2
1,1,feat(deployment): Consistent container names (...,btom1990@googlemail.com,bt,2022-12-30 16:30:28,"['docker/docker-compose.dev.yml', 'docker/dock...",3,NaN,True,12
2,2,refactor(server): imports and repository token...,jrasm91@gmail.com,Jason Rasmussen,2022-12-30 13:22:06,"['server/apps/cli/src/app.module.ts', 'server/...",81,NaN,True,130
3,3,fix nginx conf file (#1229),vedhavyas.singareddi@gmail.com,Vedhavyas Singareddi,2022-12-30 11:12:24,['nginx/nginx.conf'],1,NaN,True,4
4,4,Docs: Github -> GitHub (#1221),emaltonator@gmail.com,John P,2022-12-30 04:45:25,"['docs/docs/overview/help.md', 'docs/docs/over...",3,NaN,True,4
...,...,...,...,...,...,...,...,...,...,...
4006,4006,feat(web): improved album view UI & album card...,66187991+azroberts8@users.noreply.github.com,Andrew Roberts,2024-02-02 02:50:14,['web/src/lib/components/album-page/album-card...,3,NaN,True,6
4007,4007,chore: simplify API build (#6841),322311+benmccann@users.noreply.github.com,Ben McCann,2024-02-01 22:55:21,"['open-api/typescript-sdk/package.json', 'open...",4,NaN,True,11
4008,4008,fix(web): Admin Settings banner/scrolling issu...,66187991+azroberts8@users.noreply.github.com,Andrew Roberts,2024-02-01 21:05:30,['web/src/routes/admin/system-settings/+page.s...,1,NaN,True,44
4009,4009,docs: provide details on storage engine album ...,50788000+mmomjian@users.noreply.github.com,mmomjian,2024-02-01 03:28:30,['docs/docs/partials/_storage-template.md'],1,NaN,True,1
4010,4010,docs(ml): hardware acceleration (#6821),101130780+mertalev@users.noreply.github.com,Mert,2024-02-01 01:12:57,"['docker/hwaccel.ml.yml', 'docker/hwaccel.tran...",5,NaN,True,91

Xử lý phần Commit Data

In [ ]:
df['Contributor'] = df['Contributor'].str.extract(r'NamedUser\(login="([^"]+)"\)')

AttributeError: Can only use .str accessor with string values!

In [ ]:
df = df.drop(columns = 'Unnamed: 0')

In [ ]:
df['Updated at'] = pd.to_datetime(df['Updated at'], utc=False)
df['Updated at'] = df['Updated at'].dt.tz_localize(None)

In [ ]:
df['Author_name'] = df['Author_name'].str.replace(r'[^a-zA-Z\s]', '', regex=True)
df

,Commit_message,Author_email,Author_name,Updated at,Files_changed,Files_changed_count,Contributor,All_checks_passed,Additions
0,fix(web): pick deleted user (#1237),jrasm91@gmail.com,Jason Rasmussen,2022-12-31 03:30:48,['web/src/lib/components/album-page/user-selec...,1,NaN,True,2
1,feat(deployment): Consistent container names (...,btom1990@googlemail.com,bt,2022-12-30 16:30:28,"['docker/docker-compose.dev.yml', 'docker/dock...",3,NaN,True,12
2,refactor(server): imports and repository token...,jrasm91@gmail.com,Jason Rasmussen,2022-12-30 13:22:06,"['server/apps/cli/src/app.module.ts', 'server/...",81,NaN,True,130
3,fix nginx conf file (#1229),vedhavyas.singareddi@gmail.com,Vedhavyas Singareddi,2022-12-30 11:12:24,['nginx/nginx.conf'],1,NaN,True,4
4,Docs: Github -> GitHub (#1221),emaltonator@gmail.com,John P,2022-12-30 04:45:25,"['docs/docs/overview/help.md', 'docs/docs/over...",3,NaN,True,4
...,...,...,...,...,...,...,...,...,...
4006,feat(web): improved album view UI & album card...,66187991+azroberts8@users.noreply.github.com,Andrew Roberts,2024-02-02 02:50:14,['web/src/lib/components/album-page/album-card...,3,NaN,True,6
4007,chore: simplify API build (#6841),322311+benmccann@users.noreply.github.com,Ben McCann,2024-02-01 22:55:21,"['open-api/typescript-sdk/package.json', 'open...",4,NaN,True,11
4008,fix(web): Admin Settings banner/scrolling issu...,66187991+azroberts8@users.noreply.github.com,Andrew Roberts,2024-02-01 21:05:30,['web/src/routes/admin/system-settings/+page.s...,1,NaN,True,44
4009,docs: provide details on storage engine album ...,50788000+mmomjian@users.noreply.github.com,mmomjian,2024-02-01 03:28:30,['docs/docs/partials/_storage-template.md'],1,NaN,True,1
4010,docs(ml): hardware acceleration (#6821),101130780+mertalev@users.noreply.github.com,Mert,2024-02-01 01:12:57,"['docker/hwaccel.ml.yml', 'docker/hwaccel.tran...",5,NaN,True,91

In [ ]:
df.dtypes

Commit_message                 object
Author_email                   object
Author_name                    object
Updated at             datetime64[ns]
Files_changed                  object
Files_changed_count             int64
Contributor                    object
All_checks_passed                bool
Additions                       int64
dtype: object

In [ ]:
df['Additions'] = df['Additions'].str.split('(', expand=True)[1].str.rstrip(',)').astype(int)

In [ ]:
df.dtypes

Commit_message                 object
Author_email                   object
Author_name                    object
Updated at             datetime64[ns]
Files_changed                  object
Files_changed_count             int64
Contributor                    object
All_checks_passed                bool
Additions                       int64
dtype: object

In [ ]:
df.to_csv('commit_data.csv')

In [ ]:
df

,Unnamed: 0,Commit_message,Author_email,Author_name,Updated at,Files_changed,Files_changed_count,Contributor,All_checks_passed,Additions
0,0,fix(web): pick deleted user (#1237),jrasm91@gmail.com,Jason Rasmussen,2022-12-31 03:30:48,['web/src/lib/components/album-page/user-selec...,1,jrasm91,True,2
1,1,feat(deployment): Consistent container names (...,btom1990@googlemail.com,bt,2022-12-30 16:30:28,"['docker/docker-compose.dev.yml', 'docker/dock...",3,bt90,True,12
2,2,refactor(server): imports and repository token...,jrasm91@gmail.com,Jason Rasmussen,2022-12-30 13:22:06,"['server/apps/cli/src/app.module.ts', 'server/...",81,jrasm91,True,130
3,3,fix nginx conf file (#1229),vedhavyas.singareddi@gmail.com,Vedhavyas Singareddi,2022-12-30 11:12:24,['nginx/nginx.conf'],1,vedhavyas,True,4
4,4,Docs: Github -> GitHub (#1221),emaltonator@gmail.com,John P,2022-12-30 04:45:25,"['docs/docs/overview/help.md', 'docs/docs/over...",3,Emalton,True,4
...,...,...,...,...,...,...,...,...,...,...
4006,4006,feat(web): improved album view UI & album card...,66187991+azroberts8@users.noreply.github.com,Andrew Roberts,2024-02-02 02:50:14,['web/src/lib/components/album-page/album-card...,3,azroberts8,True,6
4007,4007,chore: simplify API build (#6841),322311+benmccann@users.noreply.github.com,Ben McCann,2024-02-01 22:55:21,"['open-api/typescript-sdk/package.json', 'open...",4,benmccann,True,11
4008,4008,fix(web): Admin Settings banner/scrolling issu...,66187991+azroberts8@users.noreply.github.com,Andrew Roberts,2024-02-01 21:05:30,['web/src/routes/admin/system-settings/+page.s...,1,azroberts8,True,44
4009,4009,docs: provide details on storage engine album ...,50788000+mmomjian@users.noreply.github.com,mmomjian,2024-02-01 03:28:30,['docs/docs/partials/_storage-template.md'],1,mmomjian,True,1
4010,4010,docs(ml): hardware acceleration (#6821),101130780+mertalev@users.noreply.github.com,Mert,2024-02-01 01:12:57,"['docker/hwaccel.ml.yml', 'docker/hwaccel.tran...",5,mertalev,True,91

Xử lý phần Pull request data

In [ ]:
pr_df

,Unnamed: 0,Pr_state,Created_at,Updated_at,Additions,Commits,Merged_at
0,0,open,2024-06-08 22:16:00+00:00,2024-06-08 22:16:01+00:00,8,1,NaN
1,1,closed,2024-06-08 19:45:48+00:00,2024-06-08 19:51:37+00:00,854,1,2024-06-08 19:51:36+00:00
2,2,open,2024-06-08 18:23:28+00:00,2024-06-08 21:41:06+00:00,133,4,NaN
3,3,closed,2024-06-08 17:01:24+00:00,2024-06-08 17:55:20+00:00,2,1,2024-06-08 17:55:19+00:00
4,4,closed,2024-06-08 10:44:16+00:00,2024-06-08 10:50:15+00:00,1,1,2024-06-08 10:50:14+00:00
...,...,...,...,...,...,...,...
4318,4318,closed,2022-02-08 17:24:07+00:00,2024-03-12 15:28:50+00:00,343,2,2022-02-08 17:24:49+00:00
4319,4319,closed,2022-02-08 05:42:11+00:00,2024-02-13 22:15:20+00:00,10715,2,2022-02-08 05:42:35+00:00
4320,4320,closed,2022-02-07 02:28:28+00:00,2024-03-09 23:22:33+00:00,133,3,2022-02-07 02:31:32+00:00
4321,4321,closed,2022-02-06 18:08:06+00:00,2024-03-09 04:16:39+00:00,53,2,2022-02-06 19:06:01+00:00
4322,4322,closed,2022-02-06 06:07:43+00:00,2024-05-29 17:11:53+00:00,581,14,2022-02-06 06:07:56+00:00

In [ ]:
pr_df = pr_df.drop(columns = 'Unnamed: 0')

In [ ]:
pr_df['Updated_at'] = pd.to_datetime(pr_df['Updated_at'], utc=False)
pr_df['Updated_at'] = pr_df['Updated_at'].dt.tz_localize(None)

In [ ]:
pr_df['Created_at'] = pd.to_datetime(pr_df['Created_at'], utc=False)
pr_df['Created_at'] = pr_df['Created_at'].dt.tz_localize(None)

In [ ]:
pr_df['Merged_at'] = pd.to_datetime(pr_df['Merged_at'], utc=False)
pr_df['Merged_at'] = pr_df['Merged_at'].dt.tz_localize(None)

In [ ]:
pr_df

,Pr_state,Created_at,Updated_at,Additions,Commits,Merged_at
0,open,2024-06-08 22:16:00,2024-06-08 22:16:01,8,1,NaT
1,closed,2024-06-08 19:45:48,2024-06-08 19:51:37,854,1,2024-06-08 19:51:36
2,open,2024-06-08 18:23:28,2024-06-08 21:41:06,133,4,NaT
3,closed,2024-06-08 17:01:24,2024-06-08 17:55:20,2,1,2024-06-08 17:55:19
4,closed,2024-06-08 10:44:16,2024-06-08 10:50:15,1,1,2024-06-08 10:50:14
...,...,...,...,...,...,...
4318,closed,2022-02-08 17:24:07,2024-03-12 15:28:50,343,2,2022-02-08 17:24:49
4319,closed,2022-02-08 05:42:11,2024-02-13 22:15:20,10715,2,2022-02-08 05:42:35
4320,closed,2022-02-07 02:28:28,2024-03-09 23:22:33,133,3,2022-02-07 02:31:32
4321,closed,2022-02-06 18:08:06,2024-03-09 04:16:39,53,2,2022-02-06 19:06:01
4322,closed,2022-02-06 06:07:43,2024-05-29 17:11:53,581,14,2022-02-06 06:07:56

In [ ]:
pr_df.loc[pr_df['Merged_at'].isnull() & (pr_df['Pr_state'] == 'closed'), 'Merged_at'] = 'Rejected'

/tmp/ipykernel_6070/4010121747.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rejected' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  pr_df.loc[pr_df['Merged_at'].isnull() & (pr_df['Pr_state'] == 'closed'), 'Merged_at'] = 'Rejected'

In [ ]:
pr_df

,Pr_state,Created_at,Updated_at,Additions,Commits,Merged_at
0,open,2024-06-08 22:16:00,2024-06-08 22:16:01,8,1,NaT
1,closed,2024-06-08 19:45:48,2024-06-08 19:51:37,854,1,2024-06-08 19:51:36
2,open,2024-06-08 18:23:28,2024-06-08 21:41:06,133,4,NaT
3,closed,2024-06-08 17:01:24,2024-06-08 17:55:20,2,1,2024-06-08 17:55:19
4,closed,2024-06-08 10:44:16,2024-06-08 10:50:15,1,1,2024-06-08 10:50:14
...,...,...,...,...,...,...
4318,closed,2022-02-08 17:24:07,2024-03-12 15:28:50,343,2,2022-02-08 17:24:49
4319,closed,2022-02-08 05:42:11,2024-02-13 22:15:20,10715,2,2022-02-08 05:42:35
4320,closed,2022-02-07 02:28:28,2024-03-09 23:22:33,133,3,2022-02-07 02:31:32
4321,closed,2022-02-06 18:08:06,2024-03-09 04:16:39,53,2,2022-02-06 19:06:01
4322,closed,2022-02-06 06:07:43,2024-05-29 17:11:53,581,14,2022-02-06 06:07:56

In [ ]:
pr_df[pr_df['Merged_at'] == 'Rejected']

,Pr_state,Created_at,Updated_at,Additions,Commits,Merged_at
11,closed,2024-06-07 20:03:08,2024-06-07 20:04:14,0,40,Rejected
29,closed,2024-06-05 20:37:02,2024-06-05 20:53:14,1562,2,Rejected
62,closed,2024-06-01 08:34:54,2024-06-04 10:12:58,8,1,Rejected
65,closed,2024-05-30 21:37:34,2024-05-30 21:37:56,209,9,Rejected
84,closed,2024-05-29 13:39:31,2024-05-29 18:14:50,2,1,Rejected
...,...,...,...,...,...,...
4260,closed,2022-05-11 02:20:58,2022-05-12 13:01:26,86,2,Rejected
4262,closed,2022-05-08 13:14:21,2022-05-11 05:15:15,1,1,Rejected
4270,closed,2022-04-30 21:04:15,2022-05-03 07:00:32,222,7,Rejected
4273,closed,2022-04-28 13:19:14,2022-05-23 22:24:19,20,4,Rejected
4274,closed,2022-04-28 10:30:31,2022-05-06 10:28:06,4,1,Rejected

In [ ]:
pr_df.to_csv('pr.csv')

Xử lý phần issues data

In [ ]:
issue_df

,Unnamed: 0,Created_at,Closed_at,State,Labels,Assignees
0,0,2024-06-08 22:16:00+00:00,NaN,open,"['dependencies', 'renovate']",[]
1,1,2024-06-08 19:45:48+00:00,2024-06-08 19:51:36+00:00,closed,['📱mobile'],[]
2,2,2024-06-08 18:23:28+00:00,NaN,open,['🖥️web'],[]
3,3,2024-06-08 17:01:24+00:00,2024-06-08 17:55:19+00:00,closed,['🗄️server'],[]
4,4,2024-06-08 10:44:16+00:00,2024-06-08 10:50:14+00:00,closed,['📱mobile'],[]
...,...,...,...,...,...,...
7254,7254,2022-02-06 06:37:29+00:00,2022-02-08 06:27:24+00:00,closed,['enhancement'],[]
7255,7255,2022-02-06 06:37:24+00:00,2022-02-08 03:44:44+00:00,closed,['enhancement'],[]
7256,7256,2022-02-06 06:37:08+00:00,2022-02-06 06:50:47+00:00,closed,[],[]
7257,7257,2022-02-06 06:07:43+00:00,2022-02-06 06:07:56+00:00,closed,[],[]
7258,7258,2022-02-05 07:04:44+00:00,2022-02-06 06:26:15+00:00,closed,['feature'],['alextran1502']

In [ ]:
issue_df['Closed_at'] = pd.to_datetime(issue_df['Closed_at'], utc=False)
issue_df['Closed_at'] = issue_df['Closed_at'].dt.tz_localize(None)
issue_df['Created_at'] = pd.to_datetime(issue_df['Created_at'], utc=False)
issue_df['Created_at'] = issue_df['Created_at'].dt.tz_localize(None)

In [ ]:
issue_df = issue_df.drop(columns ='Unnamed: 0')

In [ ]:
issue_df.loc[issue_df['Closed_at'] == 'Not yet closed', 'Closed_at'].isnull()

0       False
2       False
7       False
12      False
14      False
        ...
5935    False
5956    False
6388    False
6785    False
7123    False
Name: Closed_at, Length: 437, dtype: bool

In [ ]:
issue_df

,Created_at,Closed_at,State,Labels,Assignees
0,2024-06-08 22:16:00,Not yet closed,open,"['dependencies', 'renovate']",[]
1,2024-06-08 19:45:48,2024-06-08 19:51:36,closed,['📱mobile'],[]
2,2024-06-08 18:23:28,Not yet closed,open,['🖥️web'],[]
3,2024-06-08 17:01:24,2024-06-08 17:55:19,closed,['🗄️server'],[]
4,2024-06-08 10:44:16,2024-06-08 10:50:14,closed,['📱mobile'],[]
...,...,...,...,...,...
7254,2022-02-06 06:37:29,2022-02-08 06:27:24,closed,['enhancement'],[]
7255,2022-02-06 06:37:24,2022-02-08 03:44:44,closed,['enhancement'],[]
7256,2022-02-06 06:37:08,2022-02-06 06:50:47,closed,[],[]
7257,2022-02-06 06:07:43,2022-02-06 06:07:56,closed,[],[]
7258,2022-02-05 07:04:44,2022-02-06 06:26:15,closed,['feature'],['alextran1502']

In [ ]:
issue_df.to_csv('issue.csv')

In [ ]:
languages = repo.get_languages()

# Tính tổng số dòng mã
total_lines = sum(languages.values())

# Tính phần trăm cho mỗi ngôn ngữ và in ra kết quả
language_data = [
    {'language': language, 'lines': lines, 'percentage': (lines / total_lines) * 100}
    for language, lines in languages.items()
]

# Tạo DataFrame từ danh sách
df = pd.DataFrame(language_data)

# Lưu DataFrame vào file CSV
csv_file = 'languages.csv'
df.to_csv(csv_file, index=False)

In [ ]:
contents = repo.get_contents("")

# Duyệt qua các file và tính kích thước
file_sizes = {}
for content_file in contents:
    if content_file.type == "file":
        file_sizes[content_file.name] = content_file.size

# In kích thước các file
for file_name, file_size in file_sizes.items():
    print(f"{file_name}: {file_size} bytes")

.dockerignore: 362 bytes
.editorconfig: 321 bytes
.gitattributes: 390 bytes
.gitignore: 378 bytes
.gitmodules: 190 bytes
CODEOWNERS: 111 bytes
CODE_OF_CONDUCT.md: 5221 bytes
LICENSE: 32388 bytes
Makefile: 1056 bytes
README.md: 5512 bytes
SECURITY.md: 107 bytes
install.sh: 2890 bytes
localizely.yml: 3222 bytes
renovate.json: 2021 bytes